### ISSUE TITLE
Version 1.1 on PyPI?

### ISSUE THREAD

**Issue by danielrichman** [tjfontaine/linode-python#23]
@rtucker https://github.com/tjfontaine/linode-python/issues/6#issuecomment-5408800

I don't know whether you consider version 1.1 to be finished, but if so, could you please update PyPI?

Thanks,
Daniel

**Comment by danielrichman** [comment]
Minoir feature request: if you did this [this](https://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) then one could say

`pip install linode-python[requests]`

This would be the same as just saying `pip install linode-python requests`, though it makes it more obvious (in a project's `requirements.txt`, say) why you're doing it, and documents the optional dependency in `setup.py`, which is nice?

Perhaps something like this (haven't tested this, sorry, YMMV:)

```git
diff --git a/setup.py b/setup.py
index e5ab297..b09d728 100644
--- a/setup.py
+++ b/setup.py
@@ -8,4 +8,5 @@ setup(
     author_email = "tjfontaine@gmail.com",
     url = "https://github.com/tjfontaine/linode-python",
     packages = ['linode'],
+    extras_require = {"requests": ["requests"]},
 )
```

**Comment by rtucker** [comment]
I balked the v1.1 release, so here's v1.1.1 :-)

Thanks for the poke.  Needs to happen every so often.
