### ISSUE TITLE
Completely broke on Debian

### ISSUE THREAD

**Issue by mabushey** [tjfontaine/linode-python#27]
⇒ git clone https://github.com/tjfontaine/linode-python.git
⇒ cd linode-python
⇒ sudo ./setup.py
from: can't read /var/mail/distutils.core
./setup.py: 4: ./setup.py: Syntax error: newline unexpected (expecting ")")

Can someone make a .deb or something that's usable?

**Comment by irgeek** [comment]
This is because the setup.py file doesn't have a shebang. Run "sudo python setup.py" instead and it should work.

**Comment by mabushey** [comment]
`python setup.py build` and then `python setup.py install` worked. Thanks. :)
